# typed: false
# frozen_string_literal: true

# Eresus Sentinel — Homebrew Formula
# Auto-generated by CI. Do not edit manually.
# See: https://github.com/EresusSecurity/Eresus-sentinel
# Tap: https://github.com/EresusSecurity/homebrew-tap

class Sentinel < Formula
  desc "Deterministic AI security toolkit — model scanning, prompt firewalls, MCP/agent security"
  homepage "https://eresussec.com"
  license "LicenseRef-ESL-1.1"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/EresusSecurity/Eresus-sentinel/releases/download/v#{version}/sentinel-#{version}.arm64_monterey.bottle.tar.gz"
      sha256 "PLACEHOLDER_ARM64_SHA256"
    else
      url "https://github.com/EresusSecurity/Eresus-sentinel/releases/download/v#{version}/sentinel-#{version}.x86_64_monterey.bottle.tar.gz"
      sha256 "PLACEHOLDER_X86_SHA256"
    end
  end

  on_linux do
    url "https://github.com/EresusSecurity/Eresus-sentinel/releases/download/v#{version}/sentinel-#{version}-linux-x86_64.tar.gz"
    sha256 "PLACEHOLDER_LINUX_SHA256"
  end

  bottle do
    root_url "https://github.com/EresusSecurity/Eresus-sentinel/releases/download/v#{version}"
  end

  def install
    bin.install "sentinel"
  end

  def caveats
    <<~EOS
      Eresus Sentinel has been installed.

      Quick start:
        sentinel --help
        sentinel scan ./my-model.pkl
        sentinel aibom .

      Documentation:
        https://eresussec.com/docs

    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sentinel --version")
    assert_match "Usage:", shell_output("#{bin}/sentinel --help")
  end
end
